--	DROP TABLES
DROP TABLE FUSECHUDA.DIRECCION_USUARIO
DROP TABLE FUSECHUDA.USUARIO
DROP TABLE FUSECHUDA.ENVIO_MENSAJERIA
DROP TABLE FUSECHUDA.REPARTIDOR
DROP TABLE FUSECHUDA.PAQUETE
DROP TABLE FUSECHUDA.MEDIO_PAGO
DROP TABLE FUSECHUDA.PEDIDO
DROP TABLE FUSECHUDA.HORARIO_LOCAL
DROP TABLE FUSECHUDA.PRODUCTO_LOCAL
DROP TABLE FUSECHUDA.[LOCAL]
DROP TABLE FUSECHUDA.CUPON
DROP TABLE FUSECHUDA.CUPON_RECLAMO
DROP TABLE FUSECHUDA.RECLAMO
DROP TABLE FUSECHUDA.OPERADOR_RECLAMO

DROP SCHEMA FUSECHUDA
