-------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------Sección 1--------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------

-- En esta sección se borrarán los objetos previamente creados
-- Esto es debido a que durante el desarrollo puede ser que se ejecute este script repetidas veces
-- Sin borrar los objetos antiguos SQL Server no permitirá la ejecución y por tal motivo se realiza esta primera sección
-- Esta sección no incide de manera relevante en la performance de la ejecución.

-- Borrado de Índices


-- Borrado de Triggers


-- Borrado de tablas
IF OBJECT_ID('FUSECHUDA.CUPON_PEDIDOS','U') IS NOT NULL
  DROP TABLE FUSECHUDA.CUPON_PEDIDOS
IF OBJECT_ID('FUSECHUDA.CUPON_RECLAMO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.CUPON_RECLAMO
IF OBJECT_ID('FUSECHUDA.CUPON_DESCUENTO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.CUPON_DESCUENTO
IF OBJECT_ID('FUSECHUDA.TIPO_CUPON','U') IS NOT NULL
  DROP TABLE FUSECHUDA.TIPO_CUPON
IF OBJECT_ID('FUSECHUDA.ENVIO_MENSAJERIA','U') IS NOT NULL
  DROP TABLE FUSECHUDA.ENVIO_MENSAJERIA
IF OBJECT_ID('FUSECHUDA.SERVICIO_MENSAJERIA','U') IS NOT NULL
  DROP TABLE FUSECHUDA.SERVICIO_MENSAJERIA
IF OBJECT_ID('FUSECHUDA.PAQUETE','U') IS NOT NULL
  DROP TABLE FUSECHUDA.PAQUETE
IF OBJECT_ID('FUSECHUDA.RECLAMO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.RECLAMO
IF OBJECT_ID('FUSECHUDA.TIPO_RECLAMO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.TIPO_RECLAMO
IF OBJECT_ID('FUSECHUDA.OPERADOR_RECLAMO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.OPERADOR_RECLAMO
IF OBJECT_ID('FUSECHUDA.PRODUCTOS_PEDIDO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.PRODUCTOS_PEDIDO
IF OBJECT_ID('FUSECHUDA.ENVIO_PEDIDO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.ENVIO_PEDIDO
IF OBJECT_ID('FUSECHUDA.PEDIDO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.PEDIDO
IF OBJECT_ID('FUSECHUDA.LOCALIDAD_REPARTIDOR','U') IS NOT NULL
  DROP TABLE FUSECHUDA.LOCALIDAD_REPARTIDOR
IF OBJECT_ID('FUSECHUDA.REPARTIDOR','U') IS NOT NULL
  DROP TABLE FUSECHUDA.REPARTIDOR
IF OBJECT_ID('FUSECHUDA.MOVILIDAD','U') IS NOT NULL
  DROP TABLE FUSECHUDA.MOVILIDAD
IF OBJECT_ID('FUSECHUDA.PRODUCTO_LOCAL','U') IS NOT NULL
  DROP TABLE FUSECHUDA.PRODUCTO_LOCAL
IF OBJECT_ID('FUSECHUDA.PRODUCTOS','U') IS NOT NULL
  DROP TABLE FUSECHUDA.PRODUCTOS
IF OBJECT_ID('FUSECHUDA.HORARIO_LOCAL','U') IS NOT NULL
  DROP TABLE FUSECHUDA.HORARIO_LOCAL
IF OBJECT_ID('FUSECHUDA.DIAS','U') IS NOT NULL
  DROP TABLE FUSECHUDA.DIAS
IF OBJECT_ID('FUSECHUDA.[LOCAL]','U') IS NOT NULL
  DROP TABLE FUSECHUDA.[LOCAL]
IF OBJECT_ID('FUSECHUDA.CATEGORIA','U') IS NOT NULL
  DROP TABLE FUSECHUDA.CATEGORIA
IF OBJECT_ID('FUSECHUDA.CATEGORIA_TIPO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.CATEGORIA_TIPO
IF OBJECT_ID('FUSECHUDA.MdeP_USUARIO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.MdeP_USUARIO
IF OBJECT_ID('FUSECHUDA.EMISOR_TARJETA','U') IS NOT NULL
  DROP TABLE FUSECHUDA.EMISOR_TARJETA
IF OBJECT_ID('FUSECHUDA.MEDIOS_DE_PAGO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.MEDIOS_DE_PAGO
IF OBJECT_ID('FUSECHUDA.DIRECCION_USUARIO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.DIRECCION_USUARIO
IF OBJECT_ID('FUSECHUDA.USUARIO','U') IS NOT NULL
  DROP TABLE FUSECHUDA.USUARIO
IF OBJECT_ID('FUSECHUDA.LOCALIDAD','U') IS NOT NULL
  DROP TABLE FUSECHUDA.LOCALIDAD
IF OBJECT_ID('FUSECHUDA.PROVINCIA','U') IS NOT NULL
  DROP TABLE FUSECHUDA.PROVINCIA


-- Borrado de Funciones


-- Borrado de Stored Procedures
IF OBJECT_ID('FUSECHUDA.MIGRAR_OPERADOR_RECLAMO') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_OPERADOR_RECLAMO
IF OBJECT_ID('FUSECHUDA.MIGRAR_USUARIO') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_USUARIO
IF OBJECT_ID('FUSECHUDA.MIGRAR_TIPO_RECLAMO') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_TIPO_RECLAMO
IF OBJECT_ID('FUSECHUDA.MIGRAR_TIPO_CUPON') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_TIPO_CUPON;
IF OBJECT_ID('FUSECHUDA.MIGRAR_MOVILIDAD') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_MOVILIDAD;
IF OBJECT_ID('FUSECHUDA.MIGRAR_EMISOR_TARJETA') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_EMISOR_TARJETA;
IF OBJECT_ID('FUSECHUDA.MIGRAR_MEDIOS_DE_PAGO') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_MEDIOS_DE_PAGO
IF OBJECT_ID('FUSECHUDA.MIGRAR_PROVINCIA') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_PROVINCIA
IF OBJECT_ID('FUSECHUDA.MIGRAR_LOCALIDAD') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_LOCALIDAD
IF OBJECT_ID('FUSECHUDA.MIGRAR_CATEGORIA_TIPO') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_CATEGORIA_TIPO
IF OBJECT_ID('FUSECHUDA.MIGRAR_CATEGORIA') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_CATEGORIA
IF OBJECT_ID('FUSECHUDA.MIGRAR_DIAS') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_DIAS
IF OBJECT_ID('FUSECHUDA.MIGRAR_PAQUETE') IS NOT NULL
  DROP PROCEDURE FUSECHUDA.MIGRAR_PAQUETEIF OBJECT_ID('FUSECHUDA.MIGRAR_LOCAL') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_LOCALIF OBJECT_ID('FUSECHUDA.MIGRAR_PRODUCTOS') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_PRODUCTOSIF OBJECT_ID('FUSECHUDA.MIGRAR_PRODUCTO_LOCAL') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_PRODUCTO_LOCALIF OBJECT_ID('FUSECHUDA.MIGRAR_HORARIO') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_HORARIOIF OBJECT_ID('FUSECHUDA.MIGRAR_REPARTIDOR') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_REPARTIDORIF OBJECT_ID('FUSECHUDA.MIGRAR_LOCALIDAD_REPARTIDOR') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_LOCALIDAD_REPARTIDORIF OBJECT_ID('FUSECHUDA.MIGRAR_MdeP_USUARIO') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_MdeP_USUARIOIF OBJECT_ID('FUSECHUDA.MIGRAR_SERVICIO_MENSAJERIA') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_SERVICIO_MENSAJERIA
IF OBJECT_ID('FUSECHUDA.MIGRAR_ENVIO_MENSAJERIA') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_ENVIO_MENSAJERIA
IF OBJECT_ID('FUSECHUDA.MIGRAR_DIRECCION_USUARIO') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_DIRECCION_USUARIO
IF OBJECT_ID('FUSECHUDA.MIGRAR_PEDIDO') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_PEDIDO
IF OBJECT_ID('FUSECHUDA.MIGRAR_ENVIO_PEDIDO') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_ENVIO_PEDIDO
IF OBJECT_ID('FUSECHUDA.MIGRAR_PRODUCTO_PEDIDO') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_PRODUCTO_PEDIDO
IF OBJECT_ID('FUSECHUDA.MIGRAR_CUPON_DESCUENTO') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_CUPON_DESCUENTO
IF OBJECT_ID('FUSECHUDA.MIGRAR_RECLAMO') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_RECLAMO
IF OBJECT_ID('FUSECHUDA.MIGRAR_CUPON_RECLAMO') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_CUPON_RECLAMO
IF OBJECT_ID('FUSECHUDA.MIGRAR_CUPON_PEDIDO') IS NOT NULL	DROP PROCEDURE FUSECHUDA.MIGRAR_CUPON_PEDIDO

-- Borrado del Schema
IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'FUSECHUDA')
  DROP SCHEMA FUSECHUDA
GO


-------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------Sección 2--------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------

-- Esta sección consiste en la creeación del Esquema, Tablas y sus respectivos Constraints
-- Dado que es posible que eventualmente se quieran crear tablas que referencian tablas que aún no fueron creadas
-- Las Foreign Keys son declaradas posteriormente mediante Alter Tables.


-- CREACION DEL ESQUEMA
-- SCHEMA
CREATE SCHEMA FUSECHUDA
GO


-- CREACION DE TABLAS DEL ESQUEMA
CREATE TABLE FUSECHUDA.PROVINCIA(
	ID_PROVINCIA [decimal](18, 0) IDENTITY(1,1) NOT NULL, 
	PROVINCIA	NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.LOCALIDAD(
	ID_LOCALIDAD [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	ID_PROVINCIA [decimal](18, 0) NOT NULL,
	LOCALIDAD	NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.USUARIO(
	ID_USUARIO [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	DNI [decimal](18, 0) NOT NULL,
	NOMBRE NVARCHAR(255) NOT NULL,
	APELLIDO NVARCHAR(255) NOT NULL,
	TELEFONO [decimal](18, 0) NULL,
	MAIL NVARCHAR(255) NOT NULL,
	FECHA_NAC [date] NOT NULL,
	FECHA_REGISTRO [datetime2](3) NOT NULL
)
GO	

CREATE TABLE FUSECHUDA.DIRECCION_USUARIO(
	ID_DIRECCION [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	ID_USUARIO [decimal](18, 0) NOT NULL,
	NOMBRE NVARCHAR(50) NOT NULL,
	DIRECCION NVARCHAR(255) NOT NULL,
	ID_LOCALIDAD [decimal](18, 0) NOT NULL,
	ID_PROVINCIA [decimal](18, 0) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.MEDIOS_DE_PAGO(
	ID_MEDIO_DE_PAGO [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	TIPO NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.EMISOR_TARJETA(
	ID_EMISOR_TARJETA [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	NOMBRE	NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.MdeP_USUARIO(
	ID [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	ID_USUARIO [decimal](18, 0) NOT NULL,
	ID_MEDIO_DE_PAGO [decimal](18, 0) NOT NULL,
	ID_EMISOR_TARJETA [decimal](18, 0) NOT NULL,
	NUMERO_TARJETA [decimal](18, 0) NULL
)
GO

CREATE TABLE FUSECHUDA.CATEGORIA_TIPO(
	ID_TIPO [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	NOMBRE	NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.CATEGORIA(
	ID_CATEGORIA [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	ID_TIPO [decimal](18, 0) NOT NULL,
	NOMBRE_CATEGORIA NVARCHAR(255)  NULL -- QUEDO EN NULL POR COMO ESTA EL STORED PROCEDURE DE MIGRACION_CATEGORIA (a revisar)
)
GO

CREATE TABLE FUSECHUDA.[LOCAL](
	ID_LOCAL [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	NOMBRE [nvarchar](100) NOT NULL,
	DESCRIPCION [nvarchar](255) NOT NULL,
	ID_CATEGORIA [decimal](18, 0) NOT NULL,
	DIRECCION [nvarchar](255) NOT NULL,
	ID_LOCALIDAD [decimal](18, 0) NOT NULL,
	ID_PROVINCIA [decimal](18, 0) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.DIAS(
	ID_DIA [decimal](18, 0) IDENTITY(1,1) NOT NULL, 
	DIA NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.HORARIO_LOCAL(
	ID_LOCAL [decimal](18, 0) NOT NULL,
	ID_DIA [decimal](18, 0) NOT NULL,
	HORA_APERTURA [decimal](18, 0) NOT NULL,
	HORA_CIERRE [decimal](18, 0) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.PRODUCTOS(
	CODIGO [nvarchar](50) NOT NULL,
	NOMBRE [nvarchar](50) NOT NULL,
	DESCRIPCION [nvarchar](255) NULL,
)
GO

CREATE TABLE FUSECHUDA.PRODUCTO_LOCAL(
	ID_LOCAL [decimal](18, 0) NOT NULL,
	CODIGO [nvarchar](50) NOT NULL,
	PRECIO [decimal](18, 2) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.MOVILIDAD(
	ID_MOVILIDAD [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	MOVILIDAD [nvarchar](50) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.REPARTIDOR(
	ID_REPARTIDOR [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	DNI [decimal](18, 0) NOT NULL,
	NOMBRE  [nvarchar](255) NOT NULL,
	APELLIDO [nvarchar](255) NOT NULL,
	TELEFONO [decimal](18, 0) NOT NULL,
	DIRECCION [nvarchar](255) NOT NULL,
	EMAIL [nvarchar](255) NOT NULL,
	FECHA_NAC [date] NOT NULL,
	ID_MOVILIDAD [decimal](18, 0) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.LOCALIDAD_REPARTIDOR(
	ID_REPARTIDOR [decimal](18, 0) NOT NULL,
	ID_LOCALIDAD [decimal](18, 0) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.PEDIDO(
	NUMERO_PEDIDO [decimal](18, 0) NOT NULL,
	ID_USUARIO [decimal](18, 0) NOT NULL,
	ID_LOCAL [decimal](18, 0) NOT NULL,
	ESTADO [nvarchar](50) NOT NULL,
	ID_MdeP_USUARIO [decimal](18, 0) NOT NULL,
	TARIFA_SERVICIO [decimal](18, 2) NULL,
	TOTAL_PRODUCTOS [decimal](18, 2) NULL,
	TOTAL_CUPONES [decimal](18, 2) NULL,
	TOTAL_SERVICIO [decimal](18, 2) NULL,
	TOTAL [decimal](18, 2) NOT NULL,
	OBSERVACIONES [nvarchar](255) NULL,
	FECHA [datetime] NOT NULL,
	CALIFICACION [decimal](18, 0) NULL	
)
GO

CREATE TABLE FUSECHUDA.ENVIO_PEDIDO(
	ID_ENVIO [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	ID_PEDIDO [decimal](18, 0) NOT NULL,
	ID_REPARTIDOR [decimal](18, 0) NOT NULL,
	ID_DIRECCION [decimal](18, 0) NOT NULL,
	PRECIO_ENVIO [decimal](18, 2) NOT NULL,
	PROPINA [decimal](18, 2) NULL,
	FECHA_ENTREGA [datetime] NULL,
	TIEMPO_ESTIMADO_ENTREGA [datetime] NULL
)
GO
   
CREATE TABLE FUSECHUDA.PRODUCTOS_PEDIDO(
	NUMERO_PEDIDO [decimal](18, 0) NOT NULL,
	CODIGO [nvarchar](50) NOT NULL,
	PRECIO [decimal](18, 2) NOT NULL,
	CANTIDAD [decimal](18, 0) NOT NULL,
	TOTAL_X_PRODUCTO [decimal](18, 2) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.PAQUETE(
	TIPO [nvarchar](50) NOT NULL,
	ALTO_MAX [decimal](18, 2) NOT NULL,
	LARGO_MAX [decimal](18, 2) NOT NULL,
	ANCHO_MAX [decimal](18, 2) NOT NULL,
	PESO_MAX [decimal](18, 2) NOT NULL,
	PRECIO [decimal](18, 2) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.OPERADOR_RECLAMO(
	ID_OPERADOR [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	NOMBRE [nvarchar](255) NOT NULL,
	APELLIDO [nvarchar](255) NOT NULL,
	DNI [decimal](18, 0) NOT NULL,
	TELEFONO [decimal](18, 0) NOT NULL,
	DIRECCION [nvarchar](255) NOT NULL,
	MAIL [nvarchar](255) NOT NULL,
	FECHA_NAC [date] NOT NULL
)
GO

CREATE TABLE FUSECHUDA.TIPO_RECLAMO(
	ID_TIPO_RECLAMO [decimal](18, 0) IDENTITY(1,1) NOT NULL, 
	TIPO_RECLAMO [nvarchar](50) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.RECLAMO(
	NUMERO_RECLAMO [decimal](18, 0) NOT NULL,
	ID_USUARIO [decimal](18, 0) NOT NULL,
	NUMERO_PEDIDO [decimal](18, 0) NOT NULL,
	FECHA [datetime] NOT NULL,
	ID_TIPO_RECLAMO [decimal](18, 0) NOT NULL,
	DESCRIPCION [nvarchar](255) NULL,
	ID_OPERADOR [decimal](18, 0) NOT NULL,
	ESTADO [nvarchar](50) NOT NULL,
	SOLUCION [nvarchar](255) NULL,
	FECHA_SOLUCION [datetime] NULL,
	CALIFICACION [decimal](18, 0) NULL
)
GO

CREATE TABLE FUSECHUDA.TIPO_CUPON(
	ID_TIPO_CUPON [decimal](18, 0) IDENTITY(1,1) NOT NULL, 
	TIPO_CUPON [nvarchar](50) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.CUPON_DESCUENTO(
	NUMERO_CUPON [decimal](18, 0) NOT NULL,
	ID_USUARIO [decimal](18, 0) NOT NULL,
	ID_TIPO [decimal](18, 0) NOT NULL,
	MONTO [decimal](18, 2) NOT NULL,
	FECHA_ALTA [datetime] NOT NULL,
	FECHA_VENCIMIENTO [datetime] NULL
)
GO

CREATE TABLE FUSECHUDA.CUPON_PEDIDOS(
	NUMERO_CUPON [decimal](18, 0) NOT NULL,
	NUMERO_PEDIDO [decimal](18, 0) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.CUPON_RECLAMO(
	NUMERO_RECLAMO [decimal](18, 0) NOT NULL,
	NUMERO_CUPON [decimal](18, 0) NOT NULL
)
GO

CREATE TABLE FUSECHUDA.SERVICIO_MENSAJERIA(
	NUMERO_MENSAJERIA [decimal](18, 0) NOT NULL,
	ID_USUARIO [decimal](18, 0) NOT NULL,
	ID_MdeP_USUARIO [decimal](18, 0) NOT NULL,
	PAQUETE_TIPO [nvarchar](50) NOT NULL,
	DIREC_ORIGEN [nvarchar](255) NOT NULL,
	DIREC_DESTINO [nvarchar](255) NOT NULL,
	DISTANCIA [decimal](18, 2) NOT NULL,
	FECHA_MENSAJERIA [datetime] NOT NULL,
	VALOR_ASEGURADO [decimal](18, 2) NOT NULL,
	PRECIO_SEGURO [decimal](18, 2) NOT NULL,
	TOTAL [decimal](18, 2) NOT NULL,
	ESTADO [nvarchar](50) NOT NULL,
	OBSERVACIONES [nvarchar](255) NULL,
	CALIFICACION [decimal](18, 0) NULL,
	ID_LOCALIDAD [decimal](18, 0) NOT NULL	
)
GO

CREATE TABLE FUSECHUDA.ENVIO_MENSAJERIA(
	ID_ENVIO [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	ID_MENSAJERIA [decimal](18, 0) NOT NULL,
	ID_REPARTIDOR [decimal](18, 0) NOT NULL,
	PRECIO_ENVIO [decimal](18, 2) NOT NULL,
	PROPINA [decimal](18, 2) NOT NULL,
	FECHA_ENTREGA [datetime] NOT NULL,
	TIEMPO_ESTIMADO_ENTREGA [datetime] NULL
)
GO


--------------------------------------------------------
---------------------Sección 2.1 -----------------------
--------------------------------------------------------

-- En esta subsección se declaran las Foreign Keys que faltó declarar en la subsección anterior

ALTER TABLE FUSECHUDA.PROVINCIA
	ADD CONSTRAINT PK_PROVINCIA PRIMARY KEY (ID_PROVINCIA)

ALTER TABLE FUSECHUDA.LOCALIDAD
	ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY (ID_LOCALIDAD),
		CONSTRAINT FK_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES FUSECHUDA.[PROVINCIA](ID_PROVINCIA)

ALTER TABLE FUSECHUDA.USUARIO
	ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)

ALTER TABLE FUSECHUDA.DIRECCION_USUARIO
	ADD CONSTRAINT PK_ID_DIRECCION_USUARIO PRIMARY KEY (ID_DIRECCION),
		CONSTRAINT FK_DIRECCION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES FUSECHUDA.[USUARIO](ID_USUARIO)

ALTER TABLE FUSECHUDA.MEDIOS_DE_PAGO
	ADD CONSTRAINT PK_MEDIO_DE_PAGO PRIMARY KEY (ID_MEDIO_DE_PAGO)

ALTER TABLE FUSECHUDA.EMISOR_TARJETA
	ADD CONSTRAINT PK_EMISOR_TARJETA PRIMARY KEY (ID_EMISOR_TARJETA)

ALTER TABLE FUSECHUDA.MdeP_USUARIO
	ADD CONSTRAINT PK_MdeP_USUARIO PRIMARY KEY (ID),
		CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES FUSECHUDA.[USUARIO](ID_USUARIO),
		CONSTRAINT FK_MEDIO_DE_PAGO FOREIGN KEY (ID_MEDIO_DE_PAGO) REFERENCES FUSECHUDA.[MEDIOS_DE_PAGO](ID_MEDIO_DE_PAGO),
		CONSTRAINT FK_EMISOR_TARJETA FOREIGN KEY (ID_EMISOR_TARJETA) REFERENCES FUSECHUDA.[EMISOR_TARJETA](ID_EMISOR_TARJETA)

ALTER TABLE FUSECHUDA.CATEGORIA_TIPO
	ADD CONSTRAINT PK_CATEGORIA_TIPO PRIMARY KEY (ID_TIPO)

ALTER TABLE FUSECHUDA.CATEGORIA
	ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA),
		CONSTRAINT FK_CATEGORIA_TIPO FOREIGN KEY (ID_TIPO) REFERENCES FUSECHUDA.[CATEGORIA_TIPO](ID_TIPO)

ALTER TABLE FUSECHUDA.[LOCAL]
	ADD	CONSTRAINT PK_LOCAL PRIMARY KEY (ID_LOCAL),
		CONSTRAINT FK_LOCAL_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES FUSECHUDA.[CATEGORIA](ID_CATEGORIA),
		CONSTRAINT FK_LOCAL_LOCALIDAD FOREIGN KEY (ID_LOCALIDAD) REFERENCES FUSECHUDA.[LOCALIDAD](ID_LOCALIDAD),
		CONSTRAINT FK_LOCAL_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES FUSECHUDA.[PROVINCIA](ID_PROVINCIA)

ALTER TABLE FUSECHUDA.DIAS
	ADD CONSTRAINT PK_DIAS PRIMARY KEY (ID_DIA)

ALTER TABLE FUSECHUDA.HORARIO_LOCAL
	ADD	CONSTRAINT PK_HORARIO_LOCAL PRIMARY KEY (ID_LOCAL, ID_DIA, HORA_APERTURA),
		CONSTRAINT FK_ID_LOCAL FOREIGN KEY (ID_LOCAL) REFERENCES FUSECHUDA.[LOCAL](ID_LOCAL),
		CONSTRAINT FK_ID_DIA FOREIGN KEY (ID_DIA) REFERENCES FUSECHUDA.[DIAS](ID_DIA)

ALTER TABLE FUSECHUDA.PRODUCTOS
	ADD	CONSTRAINT PK_PROD_CODIGO PRIMARY KEY (CODIGO)

ALTER TABLE FUSECHUDA.PRODUCTO_LOCAL
	ADD	CONSTRAINT PK_PRODUCTO_LOCAL PRIMARY KEY (ID_LOCAL, CODIGO),
		CONSTRAINT FK_PRODUCTO_LOCAL_LOCAL FOREIGN KEY (ID_LOCAL) REFERENCES FUSECHUDA.[LOCAL](ID_LOCAL)
		--CONSTRAINT FK_PRODUCTO_LOCAL_PROD_CODIGO FOREIGN KEY (CODIGO) REFERENCES FUSECHUDA.[PRODUCTOS](CODIGO)

ALTER TABLE FUSECHUDA.MOVILIDAD
	ADD	CONSTRAINT PK_MOVILIDAD PRIMARY KEY (ID_MOVILIDAD)

ALTER TABLE FUSECHUDA.REPARTIDOR
	ADD CONSTRAINT PK_REPARTIDOR PRIMARY KEY (ID_REPARTIDOR),
		CONSTRAINT FK_REPARTIDOR_MOVILIDAD FOREIGN KEY (ID_MOVILIDAD) REFERENCES FUSECHUDA.[MOVILIDAD](ID_MOVILIDAD)
		--CONSTRAINT FK_REPARTIDOR_LOCALIDAD FOREIGN KEY (ID_LOCALIDAD) REFERENCES FUSECHUDA.[LOCALIDAD](ID_LOCALIDAD)

ALTER TABLE FUSECHUDA.LOCALIDAD_REPARTIDOR
	ADD	CONSTRAINT FK_REPARTIDOR_ID FOREIGN KEY (ID_REPARTIDOR) REFERENCES FUSECHUDA.[REPARTIDOR](ID_REPARTIDOR),
		CONSTRAINT FK_LOCALIDAD_ID FOREIGN KEY (ID_LOCALIDAD) REFERENCES FUSECHUDA.[LOCALIDAD](ID_LOCALIDAD)

ALTER TABLE FUSECHUDA.PEDIDO
	ADD CONSTRAINT PK_NUMERO_PEDIDO PRIMARY KEY (NUMERO_PEDIDO),
		CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES FUSECHUDA.USUARIO(ID_USUARIO),
		CONSTRAINT FK_PEDIDO_LOCAL FOREIGN KEY (ID_LOCAL) REFERENCES FUSECHUDA.[LOCAL](ID_LOCAL),
		CONSTRAINT FK_PEDIDO_MEDIO_PAGO FOREIGN KEY (ID_MdeP_USUARIO) REFERENCES FUSECHUDA.MdeP_USUARIO(ID)

ALTER TABLE FUSECHUDA.ENVIO_PEDIDO
	ADD CONSTRAINT PK_ID_ENVIO_PEDIDO PRIMARY KEY (ID_ENVIO),
		CONSTRAINT FK_ENVIO_PEDIDO_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES FUSECHUDA.PEDIDO(NUMERO_PEDIDO),
		CONSTRAINT FK_ENVIO_PEDIDO_REPARTIDOR FOREIGN KEY (ID_REPARTIDOR) REFERENCES FUSECHUDA.[REPARTIDOR](ID_REPARTIDOR),
		CONSTRAINT FK_ENVIO_PEDIDO_DIRECCION FOREIGN KEY (ID_DIRECCION) REFERENCES FUSECHUDA.DIRECCION_USUARIO(ID_DIRECCION)
	
ALTER TABLE FUSECHUDA.PRODUCTOS_PEDIDO
	ADD	CONSTRAINT PK_PRODUCTOS_PEDIDO PRIMARY KEY (NUMERO_PEDIDO, CODIGO, CANTIDAD),
		CONSTRAINT FK_NUMERO_PEDIDO FOREIGN KEY (NUMERO_PEDIDO) REFERENCES FUSECHUDA.[PEDIDO](NUMERO_PEDIDO),
		CONSTRAINT FK_CODIGO FOREIGN KEY (CODIGO) REFERENCES FUSECHUDA.[PRODUCTOS](CODIGO)

ALTER TABLE FUSECHUDA.PAQUETE
	ADD	CONSTRAINT PK_PAQUETE PRIMARY KEY (TIPO)

ALTER TABLE FUSECHUDA.OPERADOR_RECLAMO
	ADD	CONSTRAINT PK_OPERADOR_RECLAMO PRIMARY KEY (ID_OPERADOR)

ALTER TABLE FUSECHUDA.TIPO_RECLAMO
	ADD	CONSTRAINT PK_TIPO_RECLAMO PRIMARY KEY (ID_TIPO_RECLAMO)

ALTER TABLE FUSECHUDA.TIPO_CUPON
	ADD	CONSTRAINT PK_TIPO_CUPON PRIMARY KEY (ID_TIPO_CUPON)

ALTER TABLE FUSECHUDA.RECLAMO
	ADD	CONSTRAINT PK_RECLAMO PRIMARY KEY (NUMERO_RECLAMO),
		CONSTRAINT FK_RECLAMO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES FUSECHUDA.[USUARIO](ID_USUARIO),
		CONSTRAINT FK_RECLAMO_NUMERO_PEDIDO FOREIGN KEY (NUMERO_PEDIDO) REFERENCES FUSECHUDA.[PEDIDO](NUMERO_PEDIDO),
		CONSTRAINT FK_RECLAMO_TIPO_RECLAMO FOREIGN KEY (ID_TIPO_RECLAMO) REFERENCES FUSECHUDA.[TIPO_RECLAMO](ID_TIPO_RECLAMO),
		CONSTRAINT FK_RECLAMO_OPERADOR FOREIGN KEY (ID_OPERADOR) REFERENCES FUSECHUDA.[OPERADOR_RECLAMO](ID_OPERADOR)

ALTER TABLE FUSECHUDA.CUPON_DESCUENTO
	ADD	CONSTRAINT PK_CUPON_DESCUENTO PRIMARY KEY (NUMERO_CUPON),
		CONSTRAINT FK_CUPON_DESCUENTO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES FUSECHUDA.[USUARIO](ID_USUARIO),
		CONSTRAINT FK_CUPON_DESCUENTO_TIPO FOREIGN KEY (ID_TIPO) REFERENCES FUSECHUDA.[TIPO_CUPON](ID_TIPO_CUPON)

ALTER TABLE FUSECHUDA.CUPON_PEDIDOS
	ADD	CONSTRAINT FK_CUPON_PEDIDOS_NUMERO FOREIGN KEY (NUMERO_CUPON) REFERENCES FUSECHUDA.[CUPON_DESCUENTO](NUMERO_CUPON),
		CONSTRAINT FK_CUPON_PEDIDOS_PEDIDO FOREIGN KEY (NUMERO_PEDIDO) REFERENCES FUSECHUDA.[PEDIDO](NUMERO_PEDIDO)

ALTER TABLE FUSECHUDA.CUPON_RECLAMO
	ADD	CONSTRAINT FK_NUMERO_RECLAMO FOREIGN KEY (NUMERO_RECLAMO) REFERENCES FUSECHUDA.[RECLAMO](NUMERO_RECLAMO),
		CONSTRAINT FK_NUMERO_CUPON FOREIGN KEY (NUMERO_CUPON) REFERENCES FUSECHUDA.[CUPON_DESCUENTO](NUMERO_CUPON)


ALTER TABLE FUSECHUDA.SERVICIO_MENSAJERIA
	ADD CONSTRAINT PK_SERVICIO_MENSAJERIA PRIMARY KEY (NUMERO_MENSAJERIA),
		CONSTRAINT FK_SERVICIO_MENSAJERIA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES FUSECHUDA.[USUARIO](ID_USUARIO),
		CONSTRAINT FK_SERVICIO_MENSAJERIA_MdeP FOREIGN KEY (ID_MdeP_USUARIO) REFERENCES FUSECHUDA.[MdeP_USUARIO](ID),
		CONSTRAINT FK_SERVICIO_MENSAJERIA_PAQUETE FOREIGN KEY (PAQUETE_TIPO) REFERENCES FUSECHUDA.[PAQUETE](TIPO),
		CONSTRAINT FK_SERVICIO_MENSAJERIA_LOCALIDAD FOREIGN KEY (ID_LOCALIDAD) REFERENCES FUSECHUDA.[LOCALIDAD](ID_LOCALIDAD)
		--CONSTRAINT FK_SERVICIO_MENSAJERIA_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES FUSECHUDA.[PROVINCIA](ID_PROVINCIA)


ALTER TABLE FUSECHUDA.ENVIO_MENSAJERIA
	ADD CONSTRAINT PK_ENVIO_MENSAJERIA PRIMARY KEY (ID_ENVIO),
		CONSTRAINT FK_MENSAJERIA FOREIGN KEY (ID_MENSAJERIA) REFERENCES FUSECHUDA.[SERVICIO_MENSAJERIA](NUMERO_MENSAJERIA),
		CONSTRAINT FK_REPARTIDOR FOREIGN KEY (ID_REPARTIDOR) REFERENCES FUSECHUDA.[REPARTIDOR](ID_REPARTIDOR)

-------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------Sección 3--------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------

-- En esta sección se declaran las funciones necesarias para la migración.



-------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------Sección 4--------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------

-- En esta sección se declaran las Stored Procedures para luego poder realizar la migración
-- Una Stored Procedure por cada tabla.
-- El nombre de la Stored Procedure especifica qué tabla se está migrando
-- Toda tabla cuya Primary Key es Identity, debe tener en su migración la sentencia que permite inserción de identities.


GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_OPERADOR_RECLAMO
AS
BEGIN
	INSERT INTO FUSECHUDA.OPERADOR_RECLAMO (NOMBRE, APELLIDO, DNI, TELEFONO, DIRECCION, MAIL, FECHA_NAC)
	SELECT DISTINCT OPERADOR_RECLAMO_NOMBRE, OPERADOR_RECLAMO_APELLIDO, OPERADOR_RECLAMO_DNI, OPERADOR_RECLAMO_TELEFONO, OPERADOR_RECLAMO_DIRECCION, OPERADOR_RECLAMO_MAIL, OPERADOR_RECLAMO_FECHA_NAC 	FROM gd_esquema.Maestra
	WHERE OPERADOR_RECLAMO_DNI IS NOT NULL
END
GO

CREATE PROCEDURE FUSECHUDA.MIGRAR_USUARIO
AS
BEGIN
	INSERT INTO FUSECHUDA.USUARIO (DNI, NOMBRE, APELLIDO, TELEFONO, MAIL, FECHA_NAC, FECHA_REGISTRO)
	SELECT DISTINCT USUARIO_DNI, USUARIO_NOMBRE, USUARIO_APELLIDO, USUARIO_TELEFONO, USUARIO_MAIL, USUARIO_FECHA_NAC, USUARIO_FECHA_REGISTRO FROM gd_esquema.Maestra
	WHERE USUARIO_DNI IS NOT NULL
END
GO

CREATE PROCEDURE FUSECHUDA.MIGRAR_TIPO_RECLAMO AS
BEGIN
	INSERT INTO FUSECHUDA.TIPO_RECLAMO(TIPO_RECLAMO)
	SELECT DISTINCT RECLAMO_TIPO FROM gd_esquema.Maestra WHERE RECLAMO_TIPO IS NOT NULL
END
GO

CREATE PROCEDURE FUSECHUDA.MIGRAR_TIPO_CUPON AS
BEGIN
	INSERT INTO FUSECHUDA.TIPO_CUPON(TIPO_CUPON)
	SELECT DISTINCT CUPON_TIPO FROM gd_esquema.Maestra WHERE CUPON_TIPO IS NOT NULL
END
GO

CREATE PROCEDURE FUSECHUDA.MIGRAR_MOVILIDAD AS
BEGIN
	INSERT INTO FUSECHUDA.MOVILIDAD(MOVILIDAD)
	SELECT DISTINCT REPARTIDOR_TIPO_MOVILIDAD FROM gd_esquema.Maestra WHERE REPARTIDOR_TIPO_MOVILIDAD IS NOT NULL
END
GO

CREATE PROCEDURE FUSECHUDA.MIGRAR_EMISOR_TARJETA AS
BEGIN
	INSERT INTO FUSECHUDA.EMISOR_TARJETA(NOMBRE)
	SELECT DISTINCT MARCA_TARJETA FROM gd_esquema.Maestra WHERE MARCA_TARJETA IS NOT NULL
END
GO

CREATE PROCEDURE FUSECHUDA.MIGRAR_MEDIOS_DE_PAGO AS
BEGIN
	INSERT INTO FUSECHUDA.MEDIOS_DE_PAGO(TIPO)
	SELECT DISTINCT MEDIO_PAGO_TIPO FROM gd_esquema.Maestra WHERE MEDIO_PAGO_TIPO IS NOT NULL
END
GO

CREATE PROCEDURE FUSECHUDA.MIGRAR_PROVINCIA AS
BEGIN
	INSERT INTO FUSECHUDA.PROVINCIA(PROVINCIA)
	SELECT DISTINCT NOMBRE_PROVINCIA
	FROM (
		SELECT DISTINCT DIRECCION_USUARIO_PROVINCIA as NOMBRE_PROVINCIA FROM gd_esquema.Maestra
		WHERE DIRECCION_USUARIO_PROVINCIA IS NOT NULL 
		UNION 
		SELECT DISTINCT ENVIO_MENSAJERIA_PROVINCIA as NOMBRE_PROVINCIA  FROM gd_esquema.Maestra
		WHERE ENVIO_MENSAJERIA_PROVINCIA IS NOT NULL 
		UNION 
		SELECT DISTINCT LOCAL_PROVINCIA as NOMBRE_PROVINCIA  FROM gd_esquema.Maestra
		WHERE LOCAL_PROVINCIA IS NOT NULL 
	) AS subconsulta
	GROUP BY NOMBRE_PROVINCIA
	ORDER BY NOMBRE_PROVINCIA ASC
	
	-- Ordeno alfabeticamente en este caso segun DIRECCION_USUARIO_PROVINCIA (a revisar)
	-- En este caso decidi usar subconsultas en lugar de joins porque la consulta es relativamente simple (subconsultas ya que la informacion de provincias tiene que ser usada por Usuario, Envio y Local)
	-- Usar JOIN seria adecuado si necesitaramos combinar varias tablas relacionadas por claves primarias y foráneas. Se puede especificar las condiciones de unión y obtener resultados distintos de manera más eficiente.
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_LOCALIDAD AS
BEGIN
	INSERT INTO FUSECHUDA.LOCALIDAD(ID_PROVINCIA, LOCALIDAD)
	SELECT DISTINCT ID_PROVINCIA, NOMBRE_LOCALIDAD
	FROM (
		SELECT DISTINCT PROVINCIA.ID_PROVINCIA , DIRECCION_USUARIO_LOCALIDAD AS NOMBRE_LOCALIDAD FROM gd_esquema.Maestra
		INNER JOIN FUSECHUDA.PROVINCIA ON PROVINCIA.PROVINCIA = gd_esquema.Maestra.DIRECCION_USUARIO_PROVINCIA
		WHERE DIRECCION_USUARIO_LOCALIDAD IS NOT NULL
		UNION
		SELECT DISTINCT PROVINCIA.ID_PROVINCIA, ENVIO_MENSAJERIA_LOCALIDAD AS NOMBRE_LOCALIDAD FROM gd_esquema.Maestra
		INNER JOIN FUSECHUDA.PROVINCIA ON PROVINCIA.PROVINCIA = gd_esquema.Maestra.ENVIO_MENSAJERIA_PROVINCIA
		WHERE ENVIO_MENSAJERIA_LOCALIDAD IS NOT NULL
		UNION
		SELECT DISTINCT PROVINCIA.ID_PROVINCIA , LOCAL_LOCALIDAD AS NOMBRE_LOCALIDAD FROM gd_esquema.Maestra
		INNER JOIN FUSECHUDA.PROVINCIA ON PROVINCIA.PROVINCIA = gd_esquema.Maestra.LOCAL_PROVINCIA
		WHERE LOCAL_LOCALIDAD IS NOT NULL
	) AS subconsulta
	GROUP BY ID_PROVINCIA, NOMBRE_LOCALIDAD
	ORDER BY ID_PROVINCIA ASC

END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_CATEGORIA_TIPO AS
BEGIN
	INSERT INTO FUSECHUDA.CATEGORIA_TIPO(NOMBRE)
	SELECT DISTINCT LOCAL_TIPO FROM gd_esquema.Maestra WHERE LOCAL_TIPO IS NOT NULL
END
GO

CREATE PROCEDURE FUSECHUDA.MIGRAR_CATEGORIA AS
BEGIN
	INSERT INTO FUSECHUDA.CATEGORIA(ID_TIPO, NOMBRE_CATEGORIA) VALUES
	(1, NULL),
	(1, 'Parrilla'),
	(1, 'Heladería'),
	(1, 'Comidas Rápidas'),
	(2, NULL),
	(2, 'Minimercado'),
	(2, 'Kiosco'),
	(2, 'Supermercado')
	-- "Carga  inicial" con lo que esta plasmado en el enunciado. 
	-- Se agrega opcion para los 2 tipos de categoria existentes con nombre de categoria en NULL ya que los casos que estan cargados en la tabla maestra no contemplan el nombre de categoria
	-- ¿Deberia quedar con NULL o ponemos algun texto descriptivo? 'No disponible'?
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_DIAS AS
BEGIN
	INSERT INTO FUSECHUDA.DIAS(DIA)
	SELECT DIA FROM (
	SELECT DISTINCT HORARIO_LOCAL_DIA AS DIA FROM gd_esquema.Maestra WHERE HORARIO_LOCAL_DIA IS NOT NULL ) AS DIAS
	ORDER BY 
		CASE DIA
			WHEN 'Lunes' THEN 1
			WHEN 'Martes' THEN 2
			WHEN 'Miercoles' THEN 3
			WHEN 'Jueves' THEN 4
			WHEN 'Viernes' THEN 5
			WHEN 'Sabado' THEN 6
			WHEN 'Domingo' THEN 7
		END
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_PAQUETE AS
BEGIN
	INSERT INTO FUSECHUDA.PAQUETE(TIPO, ALTO_MAX, LARGO_MAX, ANCHO_MAX, PESO_MAX, PRECIO)
	SELECT DISTINCT PAQUETE_TIPO, PAQUETE_ALTO_MAX, PAQUETE_LARGO_MAX, PAQUETE_ANCHO_MAX, PAQUETE_PESO_MAX, PAQUETE_TIPO_PRECIO from gd_esquema.Maestra
	WHERE PAQUETE_TIPO  IS NOT NULL
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_LOCAL AS
BEGIN
	INSERT INTO FUSECHUDA.[LOCAL](NOMBRE, DESCRIPCION, ID_CATEGORIA, DIRECCION, ID_PROVINCIA, ID_LOCALIDAD)
	SELECT DISTINCT LOCAL_NOMBRE, LOCAL_DESCRIPCION, cat.ID_CATEGORIA, LOCAL_DIRECCION, prov.ID_PROVINCIA, loc.ID_LOCALIDAD
	from gd_esquema.Maestra mast
	LEFT JOIN FUSECHUDA.PROVINCIA prov ON prov.PROVINCIA = mast.LOCAL_PROVINCIA
	LEFT JOIN FUSECHUDA.LOCALIDAD loc ON loc.LOCALIDAD = mast.LOCAL_LOCALIDAD AND loc.ID_PROVINCIA = prov.ID_PROVINCIA
	LEFT JOIN FUSECHUDA.CATEGORIA_TIPO tipo ON tipo.NOMBRE = mast.LOCAL_TIPO
	LEFT JOIN FUSECHUDA.CATEGORIA cat ON cat.ID_TIPO = tipo.ID_TIPO AND cat.NOMBRE_CATEGORIA IS NULL
	WHERE PRODUCTO_LOCAL_CODIGO  IS NOT NULL
END
GO


GO
CREATE PROCEDURE FUSECHUDA.MIGRAR_PRODUCTOS AS
BEGIN
	INSERT INTO FUSECHUDA.PRODUCTOS(CODIGO, NOMBRE, DESCRIPCION)
	SELECT DISTINCT PRODUCTO_LOCAL_CODIGO, PRODUCTO_LOCAL_NOMBRE, PRODUCTO_LOCAL_DESCRIPCION from gd_esquema.Maestra
	WHERE PRODUCTO_LOCAL_CODIGO  IS NOT NULL
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_PRODUCTO_LOCAL AS
BEGIN
	INSERT INTO FUSECHUDA.PRODUCTO_LOCAL(ID_LOCAL, CODIGO, PRECIO)
	SELECT DISTINCT loc.ID_LOCAL, PRODUCTO_LOCAL_CODIGO, PRODUCTO_LOCAL_PRECIO
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.[LOCAL] loc ON loc.NOMBRE = maestra.LOCAL_NOMBRE
	WHERE PRODUCTO_LOCAL_CODIGO  IS NOT NULL
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_HORARIO AS
BEGIN
	INSERT INTO FUSECHUDA.HORARIO_LOCAL(ID_LOCAL, ID_DIA, HORA_APERTURA, HORA_CIERRE)
	SELECT DISTINCT loc.ID_LOCAL, dia.ID_DIA, HORARIO_LOCAL_HORA_APERTURA, HORARIO_LOCAL_HORA_CIERRE
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.[LOCAL] loc ON loc.NOMBRE = maestra.LOCAL_NOMBRE
	LEFT JOIN FUSECHUDA.DIAS dia ON dia.DIA = maestra.HORARIO_LOCAL_DIA
	WHERE HORARIO_LOCAL_HORA_APERTURA  IS NOT NULL and HORARIO_LOCAL_HORA_CIERRE is not null
	ORDER BY loc.ID_LOCAL, DIA.ID_DIA
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_REPARTIDOR AS
BEGIN
	INSERT INTO FUSECHUDA.REPARTIDOR(DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION, EMAIL, FECHA_NAC, ID_MOVILIDAD)
	SELECT DISTINCT REPARTIDOR_DNI, REPARTIDOR_NOMBRE, REPARTIDOR_APELLIDO, REPARTIDOR_TELEFONO, REPARTIDOR_DIRECION, REPARTIDOR_EMAIL, REPARTIDOR_FECHA_NAC, mov.ID_MOVILIDAD
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.MOVILIDAD mov ON mov.MOVILIDAD = maestra.REPARTIDOR_TIPO_MOVILIDAD
	WHERE REPARTIDOR_DNI  IS NOT NULL
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_LOCALIDAD_REPARTIDOR AS
BEGIN
	INSERT INTO FUSECHUDA.LOCALIDAD_REPARTIDOR(ID_REPARTIDOR, ID_LOCALIDAD)
	SELECT DISTINCT rep.ID_REPARTIDOR, loc.ID_LOCALIDAD
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.REPARTIDOR rep ON rep.DNI = maestra.REPARTIDOR_DNI AND rep.NOMBRE = maestra.REPARTIDOR_NOMBRE AND rep.APELLIDO = maestra.REPARTIDOR_APELLIDO
	LEFT JOIN FUSECHUDA.PROVINCIA prov ON prov.PROVINCIA = maestra.LOCAL_PROVINCIA
	LEFT JOIN FUSECHUDA.LOCALIDAD loc ON loc.LOCALIDAD = maestra.LOCAL_LOCALIDAD AND loc.ID_PROVINCIA = prov.ID_PROVINCIA
	WHERE REPARTIDOR_DNI IS NOT NULL and maestra.LOCAL_PROVINCIA is not null
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_MdeP_USUARIO AS
BEGIN
	INSERT INTO FUSECHUDA.MdeP_USUARIO(ID_MEDIO_DE_PAGO, ID_USUARIO, NUMERO_TARJETA, ID_EMISOR_TARJETA)
	SELECT DISTINCT mdp.ID_MEDIO_DE_PAGO, usr.ID_USUARIO , MEDIO_PAGO_NRO_TARJETA, ID_EMISOR_TARJETA
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.MEDIOS_DE_PAGO mdp ON mdp.TIPO = maestra.MEDIO_PAGO_TIPO
	LEFT JOIN FUSECHUDA.USUARIO usr ON usr.DNI = maestra.USUARIO_DNI and usr.NOMBRE = maestra.USUARIO_NOMBRE and usr.APELLIDO = maestra.USUARIO_APELLIDO
	LEFT JOIN FUSECHUDA.EMISOR_TARJETA emisor ON emisor.NOMBRE = maestra.MARCA_TARJETA
	WHERE MEDIO_PAGO_TIPO  IS NOT NULL
	order by ID_USUARIO
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_SERVICIO_MENSAJERIA AS
BEGIN
	INSERT INTO FUSECHUDA.SERVICIO_MENSAJERIA(NUMERO_MENSAJERIA, ID_USUARIO, ID_MdeP_USUARIO, PAQUETE_TIPO, DIREC_ORIGEN, DIREC_DESTINO, DISTANCIA, FECHA_MENSAJERIA,
												VALOR_ASEGURADO, PRECIO_SEGURO, TOTAL, ESTADO, OBSERVACIONES, CALIFICACION, ID_LOCALIDAD )
	SELECT DISTINCT ENVIO_MENSAJERIA_NRO, usr.ID_USUARIO, mdpu.ID AS ID_MdeP_USUARIO, pqte.TIPO, ENVIO_MENSAJERIA_DIR_ORIG, ENVIO_MENSAJERIA_DIR_DEST, 
						ENVIO_MENSAJERIA_KM, ENVIO_MENSAJERIA_FECHA, ENVIO_MENSAJERIA_VALOR_ASEGURADO, ENVIO_MENSAJERIA_PRECIO_SEGURO, ENVIO_MENSAJERIA_TOTAL, 
						ENVIO_MENSAJERIA_ESTADO, ENVIO_MENSAJERIA_OBSERV, ENVIO_MENSAJERIA_CALIFICACION, localidad.ID_LOCALIDAD
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.USUARIO usr ON usr.DNI = maestra.USUARIO_DNI and usr.NOMBRE = maestra.USUARIO_NOMBRE and usr.APELLIDO = maestra.USUARIO_APELLIDO
	LEFT JOIN FUSECHUDA.PAQUETE pqte ON pqte.TIPO = maestra.PAQUETE_TIPO
	--LEFT JOIN FUSECHUDA.MEDIOS_DE_PAGO mdp ON mdp.TIPO = maestra.MEDIO_PAGO_TIPO 
	LEFT JOIN FUSECHUDA.MdeP_USUARIO mdpu ON mdpu.ID_USUARIO = usr.ID_USUARIO AND mdpu.NUMERO_TARJETA = maestra.MEDIO_PAGO_NRO_TARJETA --AND mdp.ID_MEDIO_DE_PAGO = mdpu.ID_MEDIO_DE_PAGO 
	LEFT JOIN FUSECHUDA.PROVINCIA prov ON prov.PROVINCIA = maestra.ENVIO_MENSAJERIA_PROVINCIA
	LEFT JOIN FUSECHUDA.LOCALIDAD localidad ON localidad.LOCALIDAD = maestra.ENVIO_MENSAJERIA_LOCALIDAD AND localidad.ID_PROVINCIA = prov.ID_PROVINCIA
	WHERE ENVIO_MENSAJERIA_NRO  IS NOT NULL
	order by ID_USUARIO
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_ENVIO_MENSAJERIA AS
BEGIN
	INSERT INTO FUSECHUDA.ENVIO_MENSAJERIA(ID_MENSAJERIA, ID_REPARTIDOR, PRECIO_ENVIO, PROPINA, FECHA_ENTREGA, TIEMPO_ESTIMADO_ENTREGA)
	SELECT DISTINCT msj.NUMERO_MENSAJERIA, rep.ID_REPARTIDOR, ENVIO_MENSAJERIA_PRECIO_ENVIO, ENVIO_MENSAJERIA_PROPINA, ENVIO_MENSAJERIA_FECHA_ENTREGA, ENVIO_MENSAJERIA_TIEMPO_ESTIMADO
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.SERVICIO_MENSAJERIA msj ON msj.NUMERO_MENSAJERIA = maestra.ENVIO_MENSAJERIA_NRO
	LEFT JOIN FUSECHUDA.REPARTIDOR rep ON rep.DNI = maestra.REPARTIDOR_DNI AND rep.NOMBRE = maestra.REPARTIDOR_NOMBRE AND rep.APELLIDO = maestra.REPARTIDOR_APELLIDO
	WHERE ENVIO_MENSAJERIA_PRECIO_ENVIO IS NOT NULL
	order by msj.NUMERO_MENSAJERIA
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_DIRECCION_USUARIO AS
BEGIN
	INSERT INTO FUSECHUDA.DIRECCION_USUARIO(ID_USUARIO, NOMBRE, DIRECCION, ID_LOCALIDAD, ID_PROVINCIA)
	SELECT DISTINCT usr.ID_USUARIO, DIRECCION_USUARIO_NOMBRE, DIRECCION_USUARIO_DIRECCION, localidad.ID_LOCALIDAD, prov.ID_PROVINCIA
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.USUARIO usr ON usr.DNI = maestra.USUARIO_DNI and usr.NOMBRE = maestra.USUARIO_NOMBRE and usr.APELLIDO = maestra.USUARIO_APELLIDO
	LEFT JOIN FUSECHUDA.PROVINCIA prov ON prov.PROVINCIA = maestra.DIRECCION_USUARIO_PROVINCIA
	LEFT JOIN FUSECHUDA.LOCALIDAD localidad ON localidad.LOCALIDAD = maestra.DIRECCION_USUARIO_LOCALIDAD AND localidad.ID_PROVINCIA = prov.ID_PROVINCIA
	WHERE DIRECCION_USUARIO_DIRECCION IS NOT NULL
	order by usr.ID_USUARIO
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_PEDIDO AS
BEGIN
	INSERT INTO FUSECHUDA.PEDIDO(NUMERO_PEDIDO, ID_USUARIO, ID_LOCAL, ESTADO, ID_MdeP_USUARIO, TARIFA_SERVICIO, TOTAL_PRODUCTOS, TOTAL_CUPONES, TOTAL_SERVICIO, 
								TOTAL, OBSERVACIONES, FECHA, CALIFICACION)
	SELECT DISTINCT PEDIDO_NRO, usr.ID_USUARIO, loc.ID_LOCAL, PEDIDO_ESTADO, mdpu.ID, PEDIDO_TARIFA_SERVICIO, PEDIDO_TOTAL_PRODUCTOS, PEDIDO_TOTAL_CUPONES, PEDIDO_TOTAL_SERVICIO, 
					PEDIDO_TOTAL_PRODUCTOS + PEDIDO_PRECIO_ENVIO + PEDIDO_PROPINA + PEDIDO_TARIFA_SERVICIO - PEDIDO_TOTAL_CUPONES as TOTAL,
					PEDIDO_OBSERV, PEDIDO_FECHA, PEDIDO_CALIFICACION
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.USUARIO usr ON usr.DNI = maestra.USUARIO_DNI and usr.NOMBRE = maestra.USUARIO_NOMBRE and usr.APELLIDO = maestra.USUARIO_APELLIDO
	LEFT JOIN FUSECHUDA.[LOCAL] loc ON loc.NOMBRE = maestra.LOCAL_NOMBRE AND loc.DIRECCION = maestra.LOCAL_DIRECCION
	LEFT JOIN FUSECHUDA.MdeP_USUARIO mdpu ON mdpu.ID_USUARIO = usr.ID_USUARIO AND mdpu.NUMERO_TARJETA = maestra.MEDIO_PAGO_NRO_TARJETA
	WHERE PEDIDO_NRO IS NOT NULL
	order by PEDIDO_NRO
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_ENVIO_PEDIDO AS
BEGIN
	INSERT INTO FUSECHUDA.ENVIO_PEDIDO(ID_PEDIDO, ID_REPARTIDOR, ID_DIRECCION, PRECIO_ENVIO, PROPINA, FECHA_ENTREGA, TIEMPO_ESTIMADO_ENTREGA)
	SELECT DISTINCT PEDIDO_NRO, rep.ID_REPARTIDOR, dir.ID_DIRECCION, PEDIDO_PRECIO_ENVIO, PEDIDO_PROPINA, PEDIDO_FECHA_ENTREGA, PEDIDO_TIEMPO_ESTIMADO_ENTREGA
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.REPARTIDOR rep ON rep.DNI = maestra.REPARTIDOR_DNI and rep.NOMBRE = maestra.REPARTIDOR_NOMBRE and rep.APELLIDO = maestra.REPARTIDOR_APELLIDO
	LEFT JOIN FUSECHUDA.PROVINCIA prov ON prov.PROVINCIA = DIRECCION_USUARIO_PROVINCIA
	LEFT JOIN FUSECHUDA.LOCALIDAD localidad ON localidad.LOCALIDAD = DIRECCION_USUARIO_LOCALIDAD AND localidad.ID_PROVINCIA = prov.ID_PROVINCIA
	LEFT JOIN FUSECHUDA.DIRECCION_USUARIO dir ON dir.DIRECCION = maestra.DIRECCION_USUARIO_DIRECCION AND dir.ID_PROVINCIA = prov.ID_PROVINCIA AND dir.ID_LOCALIDAD = localidad.ID_LOCALIDAD
	WHERE PEDIDO_NRO IS NOT NULL
	order by PEDIDO_NRO
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_PRODUCTO_PEDIDO AS
BEGIN
	INSERT INTO FUSECHUDA.PRODUCTOS_PEDIDO(NUMERO_PEDIDO, CODIGO, PRECIO, CANTIDAD, TOTAL_X_PRODUCTO)
	SELECT DISTINCT PEDIDO_NRO, PRODUCTO_LOCAL_CODIGO, PRODUCTO_LOCAL_PRECIO, PRODUCTO_CANTIDAD, PRODUCTO_LOCAL_PRECIO * PRODUCTO_CANTIDAD
	from gd_esquema.Maestra maestra
	WHERE PRODUCTO_LOCAL_CODIGO  IS NOT NULL
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_CUPON_DESCUENTO AS
BEGIN
	INSERT INTO FUSECHUDA.CUPON_DESCUENTO(NUMERO_CUPON, ID_USUARIO, ID_TIPO, MONTO, FECHA_ALTA, FECHA_VENCIMIENTO)
	SELECT DISTINCT CUPON_NRO, usr.ID_USUARIO, tipocupon.ID_TIPO_CUPON, CUPON_MONTO, CUPON_FECHA_ALTA, CUPON_FECHA_VENCIMIENTO
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.USUARIO usr ON usr.DNI = maestra.USUARIO_DNI and usr.NOMBRE = maestra.USUARIO_NOMBRE and usr.APELLIDO = maestra.USUARIO_APELLIDO
	LEFT JOIN FUSECHUDA.TIPO_CUPON tipocupon ON tipocupon.TIPO_CUPON = maestra.CUPON_TIPO
	WHERE CUPON_NRO  IS NOT NULL
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_RECLAMO AS
BEGIN
	INSERT INTO FUSECHUDA.RECLAMO(NUMERO_RECLAMO, ID_USUARIO, NUMERO_PEDIDO, FECHA, ID_TIPO_RECLAMO, ID_OPERADOR, DESCRIPCION, ESTADO, SOLUCION, FECHA_SOLUCION, CALIFICACION)
	SELECT DISTINCT RECLAMO_NRO, usr.ID_USUARIO, ped.NUMERO_PEDIDO, RECLAMO_FECHA, tiporec.ID_TIPO_RECLAMO, oper.ID_OPERADOR, RECLAMO_DESCRIPCION, RECLAMO_ESTADO, 
						RECLAMO_SOLUCION, RECLAMO_FECHA_SOLUCION, RECLAMO_CALIFICACION
	from gd_esquema.Maestra maestra
	LEFT JOIN FUSECHUDA.USUARIO usr ON usr.DNI = maestra.USUARIO_DNI and usr.NOMBRE = maestra.USUARIO_NOMBRE and usr.APELLIDO = maestra.USUARIO_APELLIDO
	LEFT JOIN FUSECHUDA.PEDIDO ped ON ped.NUMERO_PEDIDO = maestra.PEDIDO_NRO
	LEFT JOIN FUSECHUDA.TIPO_RECLAMO tiporec ON tiporec.TIPO_RECLAMO = maestra.RECLAMO_TIPO
	LEFT JOIN FUSECHUDA.OPERADOR_RECLAMO oper ON oper.DNI = maestra.OPERADOR_RECLAMO_DNI and oper.NOMBRE = maestra.OPERADOR_RECLAMO_NOMBRE and oper.APELLIDO = maestra.OPERADOR_RECLAMO_APELLIDO
	WHERE RECLAMO_NRO  IS NOT NULL
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_CUPON_RECLAMO AS
BEGIN
	INSERT INTO FUSECHUDA.CUPON_RECLAMO(NUMERO_RECLAMO, NUMERO_CUPON)
	SELECT DISTINCT RECLAMO_NRO, CUPON_NRO
	from gd_esquema.Maestra maestra
	WHERE RECLAMO_NRO IS NOT NULL AND CUPON_NRO IS NOT NULL
END
GO


CREATE PROCEDURE FUSECHUDA.MIGRAR_CUPON_PEDIDO AS
BEGIN
	INSERT INTO FUSECHUDA.CUPON_PEDIDOS(NUMERO_CUPON, NUMERO_PEDIDO)
	SELECT DISTINCT CUPON_NRO, PEDIDO_NRO
	from gd_esquema.Maestra maestra
	WHERE CUPON_NRO IS NOT NULL AND PEDIDO_NRO IS NOT NULL
END
GO

-------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------Sección 5--------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------

-- En esta sección se crean los índices necesarios para mejorar la performance de la migración


-------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------Sección 6--------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------

-- En esta sección se ejecutan todas las stored procedures para migración.
EXEC FUSECHUDA.MIGRAR_OPERADOR_RECLAMOEXEC FUSECHUDA.MIGRAR_USUARIOEXEC FUSECHUDA.MIGRAR_TIPO_RECLAMOEXEC FUSECHUDA.MIGRAR_TIPO_CUPONEXEC FUSECHUDA.MIGRAR_MOVILIDADEXEC FUSECHUDA.MIGRAR_EMISOR_TARJETAEXEC FUSECHUDA.MIGRAR_MEDIOS_DE_PAGOEXEC FUSECHUDA.MIGRAR_PROVINCIAEXEC FUSECHUDA.MIGRAR_LOCALIDADEXEC FUSECHUDA.MIGRAR_CATEGORIA_TIPOEXEC FUSECHUDA.MIGRAR_CATEGORIAEXEC FUSECHUDA.MIGRAR_DIASEXEC FUSECHUDA.MIGRAR_PAQUETEEXEC FUSECHUDA.MIGRAR_LOCALEXEC FUSECHUDA.MIGRAR_PRODUCTOSEXEC FUSECHUDA.MIGRAR_PRODUCTO_LOCALEXEC FUSECHUDA.MIGRAR_HORARIOEXEC FUSECHUDA.MIGRAR_REPARTIDOREXEC FUSECHUDA.MIGRAR_LOCALIDAD_REPARTIDOREXEC FUSECHUDA.MIGRAR_MdeP_USUARIOEXEC FUSECHUDA.MIGRAR_SERVICIO_MENSAJERIA
EXEC FUSECHUDA.MIGRAR_ENVIO_MENSAJERIA
EXEC FUSECHUDA.MIGRAR_DIRECCION_USUARIO
EXEC FUSECHUDA.MIGRAR_PEDIDO
EXEC FUSECHUDA.MIGRAR_ENVIO_PEDIDO
EXEC FUSECHUDA.MIGRAR_PRODUCTO_PEDIDO
EXEC FUSECHUDA.MIGRAR_CUPON_DESCUENTO
EXEC FUSECHUDA.MIGRAR_RECLAMO
EXEC FUSECHUDA.MIGRAR_CUPON_RECLAMO
EXEC FUSECHUDA.MIGRAR_CUPON_PEDIDO
GO
