--SELECT TOP 1000 * FROM gd_esquema.Maestra

CREATE SCHEMA FUSECHUDA
GO

CREATE TABLE FUSECHUDA.USUARIO(
	NRO INT IDENTITY(1,1) NOT NULL,
	NOMBRE NVARCHAR(255) NOT NULL,
	APELLIDO NVARCHAR(255) NOT NULL,
	DNI DECIMAL(18,0) NOT NULL,
	TELEFONO DECIMAL(18,0) NOT NULL,
	MAIL NVARCHAR(255) NOT NULL,
	FECHA_NAC [date] NOT NULL,
	FECHA_REGISTRO [datetime2](3) NOT NULL
)	
ALTER TABLE FUSECHUDA.USUARIO
	ADD CONSTRAINT PK_USUARIO PRIMARY KEY (NRO)

--SELECT * FROM FUSECHUDA.USUARIO
INSERT INTO FUSECHUDA.USUARIO --(NOMBRE, APELLIDO, DNI, MAIL, TELEFONO, FECHA_NAC, FECHA_REGISTRO)
	SELECT DISTINCT USUARIO_NOMBRE, USUARIO_APELLIDO, USUARIO_DNI, USUARIO_MAIL, USUARIO_TELEFONO, USUARIO_FECHA_NAC, USUARIO_FECHA_REGISTRO 
	FROM gd_esquema.Maestra
	WHERE USUARIO_DNI IS NOT NULL
	
CREATE TABLE FUSECHUDA.ENVIO_MENSAJERIA(
	NRO [decimal](18, 0) NOT NULL,
	USUARIO INT,
	DIR_ORIG [nvarchar](255) NOT NULL,
	DIR_DEST [nvarchar](255) NOT NULL,
	KM [decimal](18, 2) NOT NULL,
	FECHA [datetime2](3) NOT NULL,
	FECHA_ENTREGA [datetime2](3) NOT NULL,
	TIEMPO_ESTIMADO [decimal](18, 2) NULL,
	PAQUETE_TIPO [nvarchar](50) NOT NULL,
	VALOR_ASEGURADO [decimal](18, 2) NOT NULL,
	OBSERV [nvarchar](255) NULL,
	PRECIO_ENVIO [decimal](18, 2) NOT NULL,
	PRECIO_SEGURO [decimal](18, 2) NOT NULL,
	REPARTIDOR INT NOT NULL,
	PROPINA [decimal](18, 2) NOT NULL,
	MEDIO_PAGO INT NOT NULL,
	TOTAL [decimal](18, 2) NOT NULL,
	ESTADO [nvarchar](50) NOT NULL,
	CALIFICACION [decimal](18, 0) NULL,
	LOCALIDAD VARCHAR(255) NOT NULL,
	PROVINCIA VARCHAR(255) NOT NULL
)
ALTER TABLE FUSECHUDA.ENVIO_MENSAJERIA
	ADD CONSTRAINT PK_ENVIO_MENSAJERIA PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.REPARTIDOR(
	NRO INT IDENTITY(1,1),
	NOMBRE  [nvarchar](255) NOT NULL,
	APELLIDO [nvarchar](255) NOT NULL,
	DNI [decimal](18, 0) NOT NULL,
	TELEFONO [decimal](18, 0) NOT NULL,
	DIRECCION [nvarchar](255) NOT NULL,
	EMAIL [nvarchar](255) NOT NULL,
	FECHA_NAC [date] NOT NULL,
	TIPO_MOVILIDAD [nvarchar](50) NOT NULL
)
ALTER TABLE FUSECHUDA.REPARTIDOR
	ADD CONSTRAINT PK_REPARTIDOR PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.PAQUETE(
	TIPO [nvarchar](50) NOT NULL,
	ALTO_MAX [decimal](18, 2) NOT NULL,
	LARGO_MAX [decimal](18, 2) NOT NULL,
	ANCHO_MAX [decimal](18, 2) NOT NULL,
	PESO_MAX [decimal](18, 2) NOT NULL,
	PRECIO [decimal](18, 2) NOT NULL
)
ALTER TABLE FUSECHUDA.PAQUETE
	ADD	CONSTRAINT PK_PAQUETE PRIMARY KEY (TIPO)

CREATE TABLE FUSECHUDA.MEDIO_PAGO(
	TIPO [nvarchar](50) NOT NULL,
	NRO_TARJETA [nvarchar](50) NULL,
	MARCA_TARJETA [nvarchar](100) NULL
)
ALTER TABLE FUSECHUDA.MEDIO_PAGO
	ADD CONSTRAINT PK_MEDIO_PAGO PRIMARY KEY (TIPO)

CREATE TABLE FUSECHUDA.PEDIDO(
	NRO [decimal](18, 0) NOT NULL,
	USUARIO INT NOT NULL,
	LOCAL_NUMERO INT NOT NULL,
	ESTADO [nvarchar](255) NOT NULL,
	MEDIO_PAGO INT NOT NULL,
	TARIFA_SERVICIO [decimal](18, 2) NULL,
	TOTAL_PRODUCTOS [decimal](18, 2) NULL,
	TOTAL_CUPONES [decimal](18, 2) NULL,
	TOTAL_SERVICIO [decimal](18, 2) NULL,
	PRECIO_ENVIO [decimal](18, 2) NULL,
	PROPINA [decimal](18, 2) NULL,
	OBSERV [nvarchar](255) NULL,
	FECHA [datetime2](3) NOT NULL,
	FECHA_ENTREGA [datetime2](3) NULL,
	TIEMPO_ESTIMADO_ENTREGA [decimal](18, 2) NULL,
	CALIFICACION [decimal](18, 0) NULL,
)
ALTER TABLE FUSECHUDA.PEDIDO
	ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NRO),
	CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (USUARIO) REFERENCES FUSECHUDA.USUARIO(NRO),
	CONSTRAINT FK_PEDIDO_LOCAL FOREIGN KEY (LOCAL_NUMERO) REFERENCES FUSECHUDA.[LOCAL](NRO),
	CONSTRAINT FK_PEDIDO_MEDIO_PAGO FOREIGN KEY (MEDIO_PAGO) REFERENCES FUSECHUDA.MEDIO_PAGO(TIPO)

CREATE TABLE FUSECHUDA.DIRECCION_USUARIO(
	CLAVE INT IDENTITY(1,1) NOT NULL,
	USUARIO INT NOT NULL,
	NOMBRE VARCHAR(255) NOT NULL,
	DIRECCION [nvarchar](50) NOT NULL, 
	LOCALIDAD [nvarchar](255) NOT NULL,
	PROVINCIA [nvarchar](255) NOT NULL
)
ALTER TABLE FUSECHUDA.DIRECCION_USUARIO
	ADD	CONSTRAINT PK_DIRECCION_USUARIO PRIMARY KEY (CLAVE),
		CONSTRAINT FK_DIRECCION_USUARIO_USUARIO FOREIGN KEY (USUARIO) REFERENCES FUSECHUDA.USUARIO(NRO)

CREATE TABLE FUSECHUDA.[LOCAL](
	NRO INT IDENTITY(1,1),
	NOMBRE [nvarchar](100) NOT NULL,
	DESCRIPCION [nvarchar](255) NOT NULL,
	TIPO [nvarchar](50) NOT NULL,
	CATEGORIA VARCHAR(255),
	DIRECCION [nvarchar](255) NOT NULL,
	LOCALIDAD [nvarchar](255) NOT NULL,
	PROVINCIA [nvarchar](255) NOT NULL
)
ALTER TABLE FUSECHUDA.[LOCAL]
	ADD	CONSTRAINT PK_LOCAL PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.HORARIO_LOCAL(
	LOCAL_NRO INT NOT NULL,
	DIA [nvarchar](50) NOT NULL,
	HORA_APERTURA [decimal](18, 0) NOT NULL,
	HORA_COERRE [decimal](18, 0) NOT NULL,
)
ALTER TABLE FUSECHUDA.HORARIO_LOCAL
	ADD	CONSTRAINT PK_HORARIO_LOCAL PRIMARY KEY (LOCAL_NRO, DIA),
		CONSTRAINT FK_HORARIO_LOCAL FOREIGN KEY (LOCAL_NRO) REFERENCES FUSECHUDA.[LOCAL](NRO)

CREATE TABLE PRODUCTO_PEDIDO(
PEDIDO_NUMERO INT,
PRODUCTO_CODIGO INT,
PRODUCTO_CANTIDAD INT
)
ALTER TABLE FUSECHUDA.PRODUCTO_PEDIDO
	ADD	CONSTRAINT PK_PRODUCTO_PEDIDO PRIMARY KEY (PEDIDO_NUMERO, PRODUCTO_CODIGO)

CREATE TABLE FUSECHUDA.PRODUCTO_LOCAL(
	LOCAL_NRO INT,
	CODIGO [nvarchar](50) NOT NULL,
	NOMBRE [nvarchar](50) NOT NULL,
	DESCRIPCION [nvarchar](50) NULL,
	PRECIO [decimal](18, 2) NOT NULL
)
ALTER TABLE FUSECHUDA.PRODUCTO_LOCAL
	ADD	CONSTRAINT PK_PRODUCTO_LOCAL PRIMARY KEY (LOCAL_NRO, CODIGO),
		CONSTRAINT FK_PRODUCTO_LOCAL FOREIGN KEY (LOCAL_NRO) REFERENCES FUSECHUDA.[LOCAL](NRO)

CREATE TABLE FUSECHUDA.CUPON(
	NRO [decimal](18, 0) NOT NULL,
	USUARIO INT NOT NULL,
	TIPO [nvarchar](50) NOT NULL,
	MONTO [decimal](18, 2) NOT NULL,
	FECHA_ALTA [datetime2](3) NOT NULL,
	FECHA_VENCIMIENTO [datetime2](3) NOT NULL
)
ALTER TABLE FUSECHUDA.CUPON
	ADD	CONSTRAINT PK_CUPON PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.OPERADOR_RECLAMO(
	NRO INT IDENTITY(1,1) NOT NULL,
	NOMBRE [nvarchar](255) NOT NULL,
	APELLIDO [nvarchar](255) NOT NULL,
	DNI [decimal](18, 0) NOT NULL,
	TELEFONO [decimal](18, 0) NOT NULL,
	DIRECCION [nvarchar](255) NOT NULL,
	MAIL [nvarchar](255) NOT NULL,
	FECHA_NAC [date] NOT NULL
)
ALTER TABLE FUSECHUDA.OPERADOR_RECLAMO
	ADD	CONSTRAINT PK_OPERADOR_RECLAMO PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.RECLAMO(
	NUMERO [decimal](18, 0) NOT NULL,
	ID_USUARIO INT NOT NULL,
	PEDIDO_NUMERO INT NOT NULL,
	FECHA [datetime2](3) NOT NULL,
	TIPO [nvarchar](50) NOT NULL,
	DESCRIPCION [nvarchar](255) NULL,
	OPERADOR_NUMERO INT NOT NULL,
	ESTADO [nvarchar](50) NOT NULL,
	SOLUCION [nvarchar](255) NULL,
	FECHA_SOLUCION [datetime2](3) NULL,
	CALIFICACION [decimal](18, 0) NULL
)
ALTER TABLE FUSECHUDA.RECLAMO
	ADD	CONSTRAINT PK_RECLAMO PRIMARY KEY (NUMERO),
		CONSTRAINT FK_RECLAMO FOREIGN KEY (OPERADOR_NUMERO) REFERENCES FUSECHUDA.OPERADOR_RECLAMO(NRO)

CREATE TABLE FUSECHUDA.CUPON_RECLAMO(
	CUPON_NRO [decimal](18, 0) NOT NULL,
	RECLAMO_NRO [decimal](18, 0) NOT NULL
)
ALTER TABLE FUSECHUDA.CUPON_RECLAMO
	ADD	CONSTRAINT PK_CUPON_RECLAMO PRIMARY KEY (CUPON_NRO, RECLAMO_NRO),
		CONSTRAINT FK_CUPON_RECLAMO FOREIGN KEY (CUPON_NRO) REFERENCES FUSECHUDA.CUPON(NRO),
		CONSTRAINT FK_CUPON_RECLAMO FOREIGN KEY (RECLAMO_NRO) REFERENCES FUSECHUDA.RECLAMO(NRO)

