--SELECT TOP 1000 * FROM gd_esquema.Maestra

CREATE SCHEMA FUSECHUDA
GO

CREATE TABLE FUSECHUDA.USUARIO(
	NRO INT IDENTITY(1,1),
	DNI VARCHAR(255),
	NOMBRE VARCHAR(255),
	APELLIDO VARCHAR(255),
	TELEFONO VARCHAR(255),
	MAIL VARCHAR(255),
	FECHA_NAC DATE,
	FECHA_REGISTRO DATE
)	
ALTER TABLE FUSECHUDA.USUARIO
	ADD CONSTRAINT PK_USUARIO PRIMARY KEY (NRO)

--SELECT * FROM FUSECHUDA.USUARIO
INSERT INTO FUSECHUDA.USUARIO --(NOMBRE, APELLIDO, DNI, MAIL, TELEFONO, FECHA_NAC, FECHA_REGISTRO)
	SELECT DISTINCT USUARIO_NOMBRE, USUARIO_APELLIDO, USUARIO_DNI, USUARIO_MAIL, USUARIO_TELEFONO, USUARIO_FECHA_NAC, USUARIO_FECHA_REGISTRO 
	FROM gd_esquema.Maestra
	WHERE USUARIO_DNI IS NOT NULL
	
CREATE TABLE FUSECHUDA.ENVIO_MENSAJERIA(
	NRO VARCHAR(255),
	USUARIO INT,
	DIR_ORIG VARCHAR(255),
	DIR_DEST VARCHAR(255),
	KM VARCHAR(255),
	FECHA DATE,
	FECHA_ENTREGA DATE,
	TIEMPO_ESTIMADO VARCHAR(255),
	PAQUETE_TIPO VARCHAR(255),
	VALOR_ASEGURADO VARCHAR(255),
	OBSERV VARCHAR(255),
	PRECIO_ENVIO VARCHAR(255),
	PRECIO_SEGURO VARCHAR(255),
	REPARTIDOR INT,
	PROPINA VARCHAR(255),
	MEDIO_PAGO INT,
	TOTAL VARCHAR(255),
	ESTADO VARCHAR(255),
	CALIFICACION VARCHAR(255),
	LOCALIDAD VARCHAR(255),
	PROVINCIA VARCHAR(255)
)
ALTER TABLE FUSECHUDA.ENVIO_MENSAJERIA
	ADD CONSTRAINT PK_ENVIO_MENSAJERIA PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.REPARTIDOR(
	NRO INT IDENTITY(1,1),
	NOMBRE  VARCHAR(255),
	APELLIDO VARCHAR(255),
	DNI VARCHAR(255),
	TELEFONO VARCHAR(255),
	DIRECCION VARCHAR(255),
	EMAIL VARCHAR(255),
	FECHA_NAC DATE,
	TIPO_MOVILIDAD VARCHAR(255)
)
ALTER TABLE FUSECHUDA.REPARTIDOR
	ADD CONSTRAINT PK_REPARTIDOR PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.PAQUETE(
	TIPO VARCHAR(255),
	ALTO_MAX VARCHAR(255),
	LARGO_MAX VARCHAR(255),
	ANCHO_MAX VARCHAR(255),
	PESO_MAX VARCHAR(255),
	PRECIO VARCHAR(255)
)
ALTER TABLE FUSECHUDA.PAQUETE
	ADD	CONSTRAINT PK_PAQUETE PRIMARY KEY (TIPO)

CREATE TABLE FUSECHUDA.MEDIO_PAGO(
	TIPO VARCHAR(255),
	NRO_TARJETA VARCHAR(255),
	MARCA_TARJETA VARCHAR(255)
)
ALTER TABLE FUSECHUDA.MEDIO_PAGO
	ADD CONSTRAINT PK_MEDIO_PAGO PRIMARY KEY (TIPO)

CREATE TABLE FUSECHUDA.PEDIDO(
	NRO VARCHAR(255),
	USUARIO INT,
	LOCAL_NUMERO INT,
	ESTADO VARCHAR(255),
	MEDIO_PAGO INT,
	TARIFA_SERVICIO VARCHAR(255),
	TOTAL_PRODUCTOS VARCHAR(255),
	TOTAL_CUPONES VARCHAR(255),
	TOTAL_SERVICIO VARCHAR(255),
	PRECIO_ENVIO VARCHAR(255),
	PROPINA VARCHAR(255),
	OBSERV VARCHAR(255),
	FECHA DATE,
	FECHA_ENTREGA DATE,
	TIEMPO_ESTIMADO_ENTREGA VARCHAR(255),
	CALIFICACION VARCHAR(255),
)
ALTER TABLE FUSECHUDA.PEDIDO
	ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.DIRECCION_USUARIO(
	CLAVE INT IDENTITY(1,1),
	USUARIO INT,
	NOMBRE VARCHAR(255),
	DIRECCION VARCHAR(255), 
	LOCALIDAD VARCHAR(255),
	PROVINCIA VARCHAR(255)
)
ALTER TABLE FUSECHUDA.DIRECCION_USUARIO
	ADD	CONSTRAINT PK_DIRECCION_USUARIO PRIMARY KEY (CLAVE),
		CONSTRAINT FK_DIRECCION_USUARIO_USUARIO FOREIGN KEY (USUARIO) REFERENCES FUSECHUDA.USUARIO(NRO)

CREATE TABLE FUSECHUDA.[LOCAL](
	NRO INT IDENTITY(1,1),
	NOMBRE VARCHAR(255),
	DESCRIPCION VARCHAR(255),
	TIPO VARCHAR(255),
	CATEGORIA VARCHAR(255),
	DIRECCION VARCHAR(255),
	LOCALIDAD VARCHAR(255),
	PROVINCIA VARCHAR(255)
)
ALTER TABLE FUSECHUDA.[LOCAL]
	ADD	CONSTRAINT PK_LOCAL PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.HORARIO_LOCAL(
	LOCAL_NRO INT,
	DIA VARCHAR(255),
	HORA_APERTURA VARCHAR(255),
	HORA_COERRE VARCHAR(255),
)
ALTER TABLE FUSECHUDA.HORARIO_LOCAL
	ADD	CONSTRAINT PK_HORARIO_LOCAL PRIMARY KEY (LOCAL_NRO, DIA),
		CONSTRAINT FK_HORARIO_LOCAL FOREIGN KEY (LOCAL_NRO) REFERENCES FUSECHUDA.[LOCAL](NRO)

CREATE TABLE PRODUCTO_PEDIDO(
PEDIDO_NUMERO INT,
PRODUCTO_CODIGO INT,
PRODUCTO_CANTIDAD INT
)
ALTER TABLE FUSECHUDA.PRODUCTO_PEDIDO
	ADD	CONSTRAINT PK_PRODUCTO_PEDIDO PRIMARY KEY (PEDIDO_NUMERO, PRODUCTO_CODIGO)

CREATE TABLE FUSECHUDA.PRODUCTO_LOCAL(
	LOCAL_NRO INT,
	CODIGO VARCHAR(255),
	NOMBRE VARCHAR(255),
	DESCRIPCION VARCHAR(255),
	PRECIO VARCHAR(255)
)
ALTER TABLE FUSECHUDA.PRODUCTO_LOCAL
	ADD	CONSTRAINT PK_PRODUCTO_LOCAL PRIMARY KEY (LOCAL_NRO, CODIGO),
		CONSTRAINT FK_PRODUCTO_LOCAL FOREIGN KEY (LOCAL_NRO) REFERENCES FUSECHUDA.[LOCAL](NRO)

CREATE TABLE FUSECHUDA.CUPON(
	NRO VARCHAR(255),
	USUARIO INT,
	TIPO VARCHAR(255),
	MONTO VARCHAR(255),
	FECHA_ALTA DATE,
	FECHA_VENCIMIENTO VARCHAR(255)
)
ALTER TABLE FUSECHUDA.CUPON
	ADD	CONSTRAINT PK_CUPON PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.OPERADOR_RECLAMO(
	NRO INT IDENTITY(1,1),
	NOMBRE VARCHAR(255),
	APELLIDO VARCHAR(255),
	DNI VARCHAR(255),
	TELEFONO VARCHAR(255),
	DIRECCION VARCHAR(255),
	MAIL VARCHAR(255),
	FECHA_NAC DATE
)
ALTER TABLE FUSECHUDA.OPERADOR_RECLAMO
	ADD	CONSTRAINT PK_OPERADOR_RECLAMO PRIMARY KEY (NRO)

CREATE TABLE FUSECHUDA.RECLAMO(
	RECLAMO_NUMERO VARCHAR(255),
	ID_USUARIO INT,
	PEDIDO_NUMERO INT,
	FECHA DATE,
	TIPO VARCHAR(255),
	DESCRIPCION VARCHAR(255),
	OPERADOR_NUMERO INT,
	ESTADO VARCHAR(255),
	SOLUCION VARCHAR(255),
	FECHA_SOLUCION DATE,
	CALIFICACION VARCHAR(255)
)
ALTER TABLE FUSECHUDA.RECLAMO
	ADD	CONSTRAINT PK_RECLAMO PRIMARY KEY (RECLAMO_NUMERO),
		CONSTRAINT FK_RECLAMO FOREIGN KEY (OPERADOR_NUMERO) REFERENCES FUSECHUDA.OPERADOR_RECLAMO(NRO)

CREATE TABLE FUSECHUDA.CUPON_RECLAMO(
	NRO VARCHAR(255),
	RECLAMO_NRO VARCHAR(255),
	TIPO VARCHAR(255),
	MONTO VARCHAR(255),
	FECHA_ALTA DATE,
	FECHA_VENCIMIENTO DATE
)
ALTER TABLE FUSECHUDA.CUPON_RECLAMO
	ADD	CONSTRAINT PK_CUPON_RECLAMO PRIMARY KEY (NRO),
		CONSTRAINT FK_CUPON_RECLAMO FOREIGN KEY (OPERADOR_NRO) REFERENCES FUSECHUDA.RECLAMO(NRO)

